# Generated by Django 6.0.6 on 2026-07-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Approved', 'Approved')], default='Draft', max_length=20),
        ),
    ]
