# Generated by Django 6.0.6 on 2026-07-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0002_appraisal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
