# Generated by Django 6.0.6 on 2026-07-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0004_departmentadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentadmin',
            name='department',
        ),
        migrations.AddField(
            model_name='departmentadmin',
            name='departments',
            field=models.JSONField(default=list, help_text='List of tagged departments'),
        ),
    ]
