# Generated by Django 6.0.6 on 2026-07-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0005_remove_departmentadmin_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentadmin',
            name='locations',
            field=models.JSONField(blank=True, default=list, help_text='List of tagged duty locations (optional)'),
        ),
    ]
