# Generated by Django 6.0.6 on 2026-08-20 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0008_branch_departmentadmin_branches_appraisal_branch_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': 'Branches'},
        ),
    ]
