# Generated by Django 6.0.6 on 2026-09-17 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0009_alter_branch_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_token', models.TextField(blank=True, default='', help_text='Meta System User Access Token')),
                ('phone_number_id', models.CharField(blank=True, default='', help_text='Meta WhatsApp Phone Number ID', max_length=100)),
                ('business_account_id', models.CharField(blank=True, default='', help_text='Meta WhatsApp Business Account ID', max_length=100)),
                ('template_name', models.CharField(default='training_assessment_reminder', help_text='Approved WhatsApp Message Template Name', max_length=100)),
                ('template_language', models.CharField(default='en_US', help_text='Template language code, e.g. en_US', max_length=20)),
                ('base_url', models.CharField(default='http://172.16.21.161:5173', help_text='App Frontend URL for assessment links', max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Configuration',
                'verbose_name_plural': 'WhatsApp Configuration',
            },
        ),
        migrations.AddField(
            model_name='departmentadmin',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='', help_text='WhatsApp phone number with country code, e.g. 919876543210', max_length=25),
        ),
        migrations.CreateModel(
            name='TrainingEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('date_of_joining', models.DateField()),
                ('training_period_months', models.IntegerField(default=1)),
                ('training_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Training', 'In Training'), ('Assessment Due', 'Assessment Due (7 Days)'), ('Completed', 'Training Completed'), ('Discontinued', 'Discontinued')], default='Training', max_length=30)),
                ('whatsapp_notification_sent', models.BooleanField(default=False)),
                ('whatsapp_notification_date', models.DateTimeField(blank=True, null=True)),
                ('whatsapp_notification_status', models.CharField(default='Pending', max_length=50)),
                ('whatsapp_error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appraisal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_record', to='appraisal.appraisal')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_employees', to='appraisal.branch')),
            ],
        ),
    ]
