# Generated by Django 6.0.6 on 2026-09-17 10:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0010_whatsappconfig_departmentadmin_whatsapp_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TraineeAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainee_code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('training_period', models.CharField(default='1 Month', max_length=50)),
                ('training_completion_date', models.DateField(blank=True, null=True)),
                ('job_knowledge', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('quality_of_work', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('productivity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('attendance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('initiative', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('communication', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('teamwork', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('adaptability', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('professionalism', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('self_improvement', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('total_score', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0.0)),
                ('performance_rating', models.CharField(blank=True, choices=[('Highly performed', 'Highly performed (85% - 100%)'), ('Well performed', 'Well performed (70% - 84%)'), ('Needs Improvement', 'Needs Improvement (50% - 69%)'), ('Unsatisfactory', 'Unsatisfactory (below 50%)')], default='', max_length=50)),
                ('employee_signature', models.CharField(blank=True, default='', max_length=100)),
                ('employee_signature_date', models.DateField(blank=True, null=True)),
                ('immediate_manager_signature', models.CharField(blank=True, default='', max_length=100)),
                ('immediate_manager_date', models.DateField(blank=True, null=True)),
                ('department_head_signature', models.CharField(blank=True, default='', max_length=100)),
                ('department_head_date', models.DateField(blank=True, null=True)),
                ('authorized_signature_1', models.CharField(blank=True, default='', max_length=100)),
                ('authorized_date_1', models.DateField(blank=True, null=True)),
                ('authorized_signature_2', models.CharField(blank=True, default='', max_length=100)),
                ('authorized_date_2', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted')], default='Submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appraisal.branch')),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainee_evaluations', to=settings.AUTH_USER_MODEL)),
                ('trainee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='appraisal.trainingemployee')),
            ],
        ),
    ]
